custom_field:
  teacher:
    - column_name: test
      data_type: int
    - column_name: test2
      data_type: varchar(255)
      include_in_create: true
      include_in_filter: true
graphql:
  exclude_field:
    teacher:
      - column_name: fk_class