var ErrRepoDataNotFoundAfterInsert = errgen.NewUnexpectedErr("Something went wrong")
var ErrRepoDataNotFoundAfterUpdate = errgen.NewUnexpectedErr("Something went wrong")
var ErrCannotParseDate = errgen.NewBadRequestErr("Cannot parse date")
var ErrCannotParseBool = errgen.NewBadRequestErr("Cannot parse bool")
var ErrCannotParsePoint = errgen.NewBadRequestErr("Cannot parse point")
var ErrCannotParseMap = errgen.NewBadRequestErr("Cannot parse map")
var ErrColumnRequiredForDTOConversion = errgen.NewUnexpectedErr("Column required to convert from Update DTO to Create DTO")
